use_frameworks!

target 'LTBarrage_Example' do
  pod 'LTBarrage', :path => '../'

  target 'LTBarrage_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
